LANGUAGE LANG_BENGALI, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "ফাইল"
RMS_NEW			equ "নতুন", 9,"Ctrl+N"
RMS_OPEN		equ "খোলা...", 9,"Ctrl+O"
RMS_SAVE		equ "সংরক্ষণ...", 9,"Ctrl+S"
RMS_SAVEAS		equ "সংরক্ষণ করুন...", 9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "সংকোচনের সাথে সংরক্ষণ করুন..."
RMS_IMPORT		equ "আমদানি...", 9,"Ctrl+I"
RMS_EXPORT		equ "রপ্তানি...", 9,"Ctrl+P"
RMS__MRU		equ "সাম্প্রতিক ব্যবহৃত ফাইলগুলি"
RMS_EXIT		equ "প্র&স্থান", 9,"Alt+F4"

RMS__EDIT		equ "সম্পাদনা"
RMS_TEST		equ "টেস্ট করুন"
RMS_DELETE		equ "মুছুন", 9,"Del"
RMS_FONTS		equ "ফন্ট সেটিংস..."
RMS_SETPATHS		equ "পাথ &সেট করুন..."
RMS_CONFIG		equ "কনফিগারেশন..."

RMS__SEARCH		equ "অনুসন্ধান"
RMS_FIND		equ "খুঁজুন...", 9,"Ctrl+F"
RMS_FINDUPWARD		equ "উপরে অনুসন্ধান করুন", 9,"Shift+F3"
RMS_FINDDOWNWARD	equ "নিচে অনুসন্ধান করুন", 9,"F3"
RMS_QUERYCONSTANT	equ "কনস্ট্যান্ট জিজ্ঞাসা করুন..."

RMS__VIEW		equ "দেখুন"
RMS_STATUSBAR		equ "স্ট্যাটাস বার"
RMS_SHOWHIDETOOLBAR	equ "টুল বার"
RMS_BINARYPANE		equ "বাইনারি"
RMS_EXPAND_ALL		equ "সব কিছু বিশদভাবে ব্যক্ত করা", 9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "সব ভেঙ্গে", 9,"Ctrl+L"
RMS_WORD_WRAP		equ "শব্দ মোড়ানো"
RMS_REFRESH		equ "রিফ্রেশ"

RMS__HELP		equ "সাহায্য"
RMS_ABOUT		equ "সম্পর্কিত..."
