LANGUAGE LANG_GERMAN, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&Datei"
RMS_NEW			equ "&Neu",			9,"Ctrl+N"
RMS_OPEN		equ "&Öffnen...",		9,"Ctrl+O"
RMS_SAVE		equ "&Speichern...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Speichern &als...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Mit &Komprimierung speichern..."
RMS_IMPORT		equ "&Importieren...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Export...",		9,"Ctrl+P"
RMS__MRU		equ "Kürzlich verwendete Dateien"
RMS_EXIT		equ "&Ausgang",			9,"Alt+F4"

RMS__EDIT		equ "&Bearbeiten"
RMS_TEST		equ "&Test machen"
RMS_DELETE		equ "&Löschen",			9,"Del"
RMS_FONTS		equ "&Schriftarteinstellungen..."
RMS_SETPATHS		equ "&Pfade festlegen..."
RMS_CONFIG		equ "&Aufbau..."

RMS__SEARCH		equ "&Suche"
RMS_FIND		equ "&Finden...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Suche nach &oben",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Suche nach &unten",	9,"F3"
RMS_QUERYCONSTANT	equ "&Abfragekonstante..."

RMS__VIEW		equ "&Aussicht"
RMS_STATUSBAR		equ "&Statusleiste"
RMS_SHOWHIDETOOLBAR	equ "&Symbolleiste"
RMS_BINARYPANE		equ "&Binär"
RMS_EXPAND_ALL		equ "Alle &erweitern",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "Alle &reduzieren",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "Zeilenumbruch"
RMS_REFRESH		equ "Aktualisierung"

RMS__HELP		equ "&Hilfe"
RMS_ABOUT		equ "&Über..."
