LANGUAGE LANG_ENGLISH, SUBLANG_DEFAULT
; some common SUBLANG_ENGLISH_* (and region codes):
;	US:		United States (US)
;	UK:		United Kingdom (GB)
;	CAN:		Canadian (CA)
;	AUS:		Australian (AU)
;	NZ:		New Zealand (NZ)
;	EIRE:		Irish (IE)
;	SOUTH_AFRICA:	South African (ZA)
;	JAMAICA:	Jamaican (JM)
;	CARIBBEAN:	Caribbean (--)
;	BELIZE:		Belize (BZ)
;	TRINIDAD:	Trinidad (TT)
;	ZIMBABWE:	Zimbabwe (ZW)
;	PHILIPPINES:	Philippine (PH)
;	INDIA:		Indian (IN)
;	MALAYSIA:	Malaysian (MY)
;	SINGAPORE:	Singaporean (SG)

; IDR_MAINMENU

RMS__FILE		equ "&File"
RMS_NEW			equ "&New",			9,"Ctrl+N"
RMS_OPEN		equ "&Open...",			9,"Ctrl+O"
RMS_SAVE		equ "&Save...",			9,"Ctrl+S"
RMS_SAVEAS		equ "Save &As...",		9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Save With Co&mpression..."
RMS_IMPORT		equ "&Import...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Export...",		9,"Ctrl+P"
RMS__MRU		equ "Recently Used Files"
RMS_EXIT		equ "E&xit",			9,"Alt+F4"

RMS__EDIT		equ "&Edit"
RMS_TEST		equ "Do &Test"
RMS_DELETE		equ "&Delete",			9,"Del"
RMS_FONTS		equ "&Font settings..."
RMS_SETPATHS		equ "Set &Paths..."
RMS_CONFIG		equ "&Configuration..."

RMS__SEARCH		equ "&Search"
RMS_FIND		equ "&Find...",			9,"Ctrl+F"
RMS_FINDUPWARD		equ "Search &Upward",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Search &Downward",		9,"F3"
RMS_QUERYCONSTANT	equ "&Query constant..."

RMS__VIEW		equ "&View"
RMS_STATUSBAR		equ "&Status Bar"
RMS_SHOWHIDETOOLBAR	equ "&Tool Bar"
RMS_BINARYPANE		equ "&Binary"
RMS_EXPAND_ALL		equ "E&xpand All",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "C&ollapse All",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "&Word Wrapping"
RMS_REFRESH		equ "Re&fresh"

RMS__HELP		equ "&Help"
RMS_ABOUT		equ "&About..."
