LANGUAGE LANG_FINNISH, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&File"
RMS_NEW			equ "&Uusi",			9,"Ctrl+N"
RMS_OPEN		equ "&Avaa...",			9,"Ctrl+O"
RMS_SAVE		equ "&Tallenna...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Tallenn&a nimellä...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Tallenna &pakattuna..."
RMS_IMPORT		equ "&Tuo...",			9,"Ctrl+I"
RMS_EXPORT		equ "&Vie...",			9,"Ctrl+P"
RMS__MRU		equ "Viimeksi käytetyt tiedostot"
RMS_EXIT		equ "P&oistu",			9,"Alt+F4"

RMS__EDIT		equ "&Muokkaus"
RMS_TEST		equ "&Testaa"
RMS_DELETE		equ "&Poista",			9,"Del"
RMS_FONTS		equ "&Fonttiasetukset..."
RMS_SETPATHS		equ "Aseta &polut..."
RMS_CONFIG		equ "&Konfiguraatio..."

RMS__SEARCH		equ "&Haku"
RMS_FIND		equ "&Etsi...",			9,"Ctrl+F"
RMS_FINDUPWARD		equ "Etsi &ylöspäin",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Etsi &alaspäin",		9,"F3"
RMS_QUERYCONSTANT	equ "&Kyselyvakio..."

RMS__VIEW		equ "&Näkymä"
RMS_STATUSBAR		equ "&Tilapalkki"
RMS_SHOWHIDETOOLBAR	equ "&Työkalupalkki"
RMS_BINARYPANE		equ "&Binaari"
RMS_EXPAND_ALL		equ "&Laajenna kaikki",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "&Tiivistä kaikki",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "&Sanan rivitys"
RMS_REFRESH		equ "&Päivitä"

RMS__HELP		equ "O&hje"
RMS_ABOUT		equ "Tietoj&a..."
