LANGUAGE LANG_FRENCH, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&Fichier"
RMS_NEW			equ "&Nouveau",			9,"Ctrl+N"
RMS_OPEN		equ "&Ouvert...",		9,"Ctrl+O"
RMS_SAVE		equ "&Sauver...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Enregistrer sous...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Économisez avec la compression..."
RMS_IMPORT		equ "&Importation...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Exportation...",		9,"Ctrl+P"
RMS__MRU		equ "Fichiers récemment utilisés"
RMS_EXIT		equ "Sortie",			9,"Alt+F4"

RMS__EDIT		equ "&Éditer"
RMS_TEST		equ "Faire un test"
RMS_DELETE		equ "Supprimer",		9,"Del"
RMS_FONTS		equ "&Paramètres de police..."
RMS_SETPATHS		equ "Définir les chemins..."
RMS_CONFIG		equ "&Configuration..."

RMS__SEARCH		equ "&Chercher"
RMS_FIND		equ "&Trouver...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Rechercher vers le haut",	9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Recherche vers le bas",	9,"F3"
RMS_QUERYCONSTANT	equ "&Constante de requête..."

RMS__VIEW		equ "&Vue"
RMS_STATUSBAR		equ "&Barre d'état"
RMS_SHOWHIDETOOLBAR	equ "&Barre d'outils"
RMS_BINARYPANE		equ "&Binaire"
RMS_EXPAND_ALL		equ "Développer tout",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "Réduire tout",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "&Habillage de mots"
RMS_REFRESH		equ "Rafraîchir"

RMS__HELP		equ "&Aidez-moi"
RMS_ABOUT		equ "&À propos de..."
