LANGUAGE LANG_HINDI, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "फ़ाइल"
RMS_NEW			equ "नई", 9,"Ctrl+N"
RMS_OPEN		equ "खोलें...", 9,"Ctrl+O"
RMS_SAVE		equ "सहेजें...", 9,"Ctrl+S"
RMS_SAVEAS		equ "इस रूप में सहेजें ...", 9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "संपीड़न के साथ सहेजें..."
RMS_IMPORT		equ "आयात...", 9,"Ctrl+I"
RMS_EXPORT		equ "निर्यात...", 9,"Ctrl+P"
RMS__MRU		equ "हाल ही में प्रयुक्त फ़ाइलें"
RMS_EXIT		equ "बा&हर निकलें", 9,"Alt+F4"

RMS__EDIT		equ "संपादित करें"
RMS_TEST		equ "परी&क्षण करें"
RMS_DELETE		equ "हटाएँ", 9,"Del"
RMS_FONTS		equ "फ़ॉन्ट सेटिंग्स..."
RMS_SETPATHS		equ "पथ &सेट करें..."
RMS_CONFIG		equ "कॉन्फ़िगरेशन..."

RMS__SEARCH		equ "खोज"
RMS_FIND		equ "खोजें...", 9,"Ctrl+F"
RMS_FINDUPWARD		equ "खोज &ऊपर", 9,"Shift+F3"
RMS_FINDDOWNWARD	equ "खोज &नीचे", 9,"F3"
RMS_QUERYCONSTANT	equ "स्थिरांक की पूछताछ..."

RMS__VIEW		equ "देखें"
RMS_STATUSBAR		equ "स्टेटस बार"
RMS_SHOWHIDETOOLBAR	equ "टूल बार"
RMS_BINARYPANE		equ "बाइनरी"
RMS_EXPAND_ALL		equ "सभी का विस्तार करें", 9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "सभी को संकुचित करें", 9,"Ctrl+L"
RMS_WORD_WRAP		equ "शब्द लपेटना"
RMS_REFRESH		equ "ताज़ा &करें"

RMS__HELP		equ "मदद"
RMS_ABOUT		equ "के बारे में..."
