LANGUAGE LANG_INDONESIAN, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "Be&rkas"
RMS_NEW			equ "&Baru",			9,"Ctrl+N"
RMS_OPEN		equ "&Buka...",			9,"Ctrl+O"
RMS_SAVE		equ "Si&mpan...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Simpan Seba&gai...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Simpan dengan &Kompresi..."
RMS_IMPORT		equ "&Impor...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Ekspor...",		9,"Ctrl+P"
RMS__MRU		equ "Berkas yang Digunakan Baru-Baru ini"
RMS_EXIT		equ "Ke&luar",			9,"Alt+F4"

RMS__EDIT		equ "&Edit"
RMS_TEST		equ "Lakukan &Tes"
RMS_DELETE		equ "Ha&pus",			9,"Del"
RMS_FONTS		equ "Pengaturan &Fon..."
RMS_SETPATHS		equ "Tentukan &Jalur..."
RMS_CONFIG		equ "&Konfigurasi..."

RMS__SEARCH		equ "&Cari"
RMS_FIND		equ "&Temukan...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Cari ke &Atas",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Cari ke &Bawah",		9,"F3"
RMS_QUERYCONSTANT	equ "&Permintaan konstan..."

RMS__VIEW		equ "&Tampilan"
RMS_STATUSBAR		equ "&Bilah Status"
RMS_SHOWHIDETOOLBAR	equ "Bil&ah Alat"
RMS_BINARYPANE		equ "Bi&nary"
RMS_EXPAND_ALL		equ "&Perluas Semua",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "Ciut&kan Semua",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "Kemas Ka&ta"
RMS_REFRESH		equ "Muat &Ulang"

RMS__HELP		equ "&Bantuan"
RMS_ABOUT		equ "&Tentang..."
