LANGUAGE LANG_ITALIAN, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&File"
RMS_NEW			equ "&Nuovo",			9,"Ctrl+N"
RMS_OPEN		equ "&Apri...",			9,"Ctrl+O"
RMS_SAVE		equ "&Salva...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Salva &come...",		9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Salva con co&mpressione..."
RMS_IMPORT		equ "&Importa...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Esporta...",		9,"Ctrl+P"
RMS__MRU		equ "File usati recentemente"
RMS_EXIT		equ "E&sci",			9,"Alt+F4"

RMS__EDIT		equ "&Modifica"
RMS_TEST		equ "Effettua &test"
RMS_DELETE		equ "&Elimina",			9,"Canc"
RMS_FONTS		equ "Impostazioni &font..."
RMS_SETPATHS		equ "Impostazioni &percorsi..."
RMS_CONFIG		equ "&Impostazioni..."

RMS__SEARCH		equ "&Cerca"
RMS_FIND		equ "&Cerca...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Cerca &precedente",	9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Cerca &successivo",	9,"F3"
RMS_QUERYCONSTANT	equ "Cerca &costante..."

RMS__VIEW		equ "&Visualizza"
RMS_STATUSBAR		equ "Barra &stato"
RMS_SHOWHIDETOOLBAR	equ "Barra &strumenti"
RMS_BINARYPANE		equ "&Binario"
RMS_EXPAND_ALL		equ "E&spandi tutto",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "&Riduci tutto",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "A capo a&utomatico"
RMS_REFRESH		equ "A&ggiorna"

RMS__HELP		equ "&?"
RMS_ABOUT		equ "&Info sul programma..."
