LANGUAGE LANG_JAPANESE, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "ファイル(&F)"
RMS_NEW			equ "新規作成(&N)",		9,"Ctrl+N"
RMS_OPEN		equ "開く(&O)...",		9,"Ctrl+O"
RMS_SAVE		equ "上書き保存(&S)...",		9,"Ctrl+S"
RMS_SAVEAS		equ "名前を付けて保存(&A)...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "名前を付けて圧縮保存(&M)..."
RMS_IMPORT		equ "インポート(&I)...",		9,"Ctrl+I"
RMS_EXPORT		equ "エクスポート(&E)...",		9,"Ctrl+P"
RMS__MRU		equ "最近使ったファイル(&R)"
RMS_EXIT		equ "終了(&X)",			9,"Alt+F4"

RMS__EDIT		equ "編集(&E)"
RMS_TEST		equ "テストする(&T)"
RMS_DELETE		equ "削除(&D)",			9,"Del"
RMS_FONTS		equ "フォント設定(&F)..."
RMS_SETPATHS		equ "PATHの設定(&P)..."
RMS_CONFIG		equ "設定(&C)..."

RMS__SEARCH		equ "検索(&S)"
RMS_FIND		equ "検索(&F)...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "上検索(&U)",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "下検索(&D)",		9,"F3"
RMS_QUERYCONSTANT	equ "定数を問い合わせ(&Q)"

RMS__VIEW		equ "表示(&V)"
RMS_STATUSBAR		equ "ステータス バー(&S)"
RMS_SHOWHIDETOOLBAR	equ "ツール バー(&T)"
RMS_BINARYPANE		equ "バイナリー(&B)"
RMS_EXPAND_ALL		equ "すべて展開(&X)",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "すべて折りたたむ(&O)",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "行を折り返す(&W)"
RMS_REFRESH		equ "最新の情報に更新(&F)"

RMS__HELP		equ "ヘルプ(&H)"
RMS_ABOUT		equ "バージョン情報(&A)..."
