LANGUAGE LANG_KOREAN, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "파일(&F)"
RMS_NEW			equ "새로 만들기(&N)",		9,"Ctrl+N"
RMS_OPEN		equ "열기(&O)...",		9,"Ctrl+O"
RMS_SAVE		equ "저장(&S)...",		9,"Ctrl+S"
RMS_SAVEAS		equ "다른 이름으로 저장(&A)...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "압축으로 저장(&M)..."
RMS_IMPORT		equ "가져오기(&I)...",		9,"Ctrl+I"
RMS_EXPORT		equ "내보내기(&E)...",		9,"Ctrl+P"
RMS__MRU		equ "최근에 사용한 파일"
RMS_EXIT		equ "종료(&X)",			9,"Alt+F4"

RMS__EDIT		equ "편집(&E)"
RMS_TEST		equ "테스트(&T)"
RMS_DELETE		equ "삭제(&D)",			9,"Del"
RMS_FONTS		equ "글꼴 설정(&F)..."
RMS_SETPATHS		equ "경로 설정(&P)..."
RMS_CONFIG		equ "구성(&C)..."

RMS__SEARCH		equ "검색(&S)"
RMS_FIND		equ "찾기(&F)...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "위로 검색(&U)",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "아래로 검색(&D)",		9,"F3"
RMS_QUERYCONSTANT	equ "쿼리 상수(&Q)..."

RMS__VIEW		equ "보기(&V)"
RMS_STATUSBAR		equ "상태 표시줄(&S)"
RMS_SHOWHIDETOOLBAR	equ "도구 모음(&T)"
RMS_BINARYPANE		equ "바이너리(&B)"
RMS_EXPAND_ALL		equ "모두 확장(&X)",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "모두 축소(&O)",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "단어 줄바꿈(&W)"
RMS_REFRESH		equ "새로 고침(&F)"

RMS__HELP		equ "도움말(&H)"
RMS_ABOUT		equ "정보(&A)..."
