LANGUAGE LANG_POLISH, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&Plik"
RMS_NEW			equ "&Nowy",			9,"Ctrl+N"
RMS_OPEN		equ "&Otwórz...",		9,"Ctrl+O"
RMS_SAVE		equ "&Zapisz...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Zapisz &jako...",		9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Zapisz z Ko&mpresją..."
RMS_IMPORT		equ "&Importuj...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Eksportuj...",		9,"Ctrl+P"
RMS__MRU		equ "Ostatnio używane pliki"
RMS_EXIT		equ "W&yjście",			9,"Alt+F4"

RMS__EDIT		equ "&Edycja"
RMS_TEST		equ "&Testuj"
RMS_DELETE		equ "&Usuń",			9,"Del"
RMS_FONTS		equ "Ustawienia &Czcionki..."
RMS_SETPATHS		equ "Ustawienia &Katalogów..."
RMS_CONFIG		equ "Konfi&guracja..."

RMS__SEARCH		equ "&Szukaj"
RMS_FIND		equ "&Szukaj...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Szukaj &W górę",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Szukaj w &dół",		9,"F3"
RMS_QUERYCONSTANT	equ "&Query constant..."

RMS__VIEW		equ "&Widok"
RMS_STATUSBAR		equ "Pasek &stanu"
RMS_SHOWHIDETOOLBAR	equ "Pasek &narzędzi"
RMS_BINARYPANE		equ "&Binarny"
RMS_EXPAND_ALL		equ "Roz&wiń wszystko",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "&Zwiń wszystko",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "Zawijanie wy&razów"
RMS_REFRESH		equ "O&dśwież"

RMS__HELP		equ "&Pomoc"
RMS_ABOUT		equ "&O programie..."
