LANGUAGE LANG_PORTUGUESE, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&Arquivo"
RMS_NEW			equ "&Novo",		9,"Ctrl+N"
RMS_OPEN		equ "&Abrir...",		9,"Ctrl+O"
RMS_SAVE		equ "&Salvar...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Salvar &Como...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Salvar com Co&mpressão..."
RMS_IMPORT		equ "Im&portar...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Exportar...",		9,"Ctrl+P"
RMS__MRU		equ "Arquivos Usados Recentemente"
RMS_EXIT		equ "Sa&ir",		9,"Alt+F4"

RMS__EDIT		equ "&Editar"
RMS_TEST		equ "&Testar"
RMS_DELETE		equ "E&xcluir",		9,"Del"
RMS_FONTS		equ "Configurações de &Fonte..."
RMS_SETPATHS		equ "Definir Camin&hos..."
RMS_CONFIG		equ "&Configuração..."

RMS__SEARCH		equ "&Pesquisar"
RMS_FIND		equ "&Localizar...",	9,"Ctrl+F"
RMS_FINDUPWARD		equ "Pesquisar &Acima",	9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Pesquisar A&baixo",	9,"F3"
RMS_QUERYCONSTANT	equ "&Consultar Constante..."

RMS__VIEW		equ "E&xibir"
RMS_STATUSBAR		equ "Barra de &Status"
RMS_SHOWHIDETOOLBAR	equ "Barra de &Ferramentas"
RMS_BINARYPANE		equ "&Binário"
RMS_EXPAND_ALL		equ "E&xpandir Todos",	9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "Rec&olher Todos",	9,"Ctrl+L"
RMS_WORD_WRAP		equ "Quebra de &Palavra"
RMS_REFRESH		equ "&Atualizar"

RMS__HELP		equ "A&juda"
RMS_ABOUT		equ "&Sobre..."
