LANGUAGE LANG_RUSSIAN, SUBLANG_DEFAULT

; IDR_MAINMENU

RMS__FILE		equ "&Файл"
RMS_NEW			equ "Со&здать",			9,"Ctrl+N"
RMS_OPEN		equ "&Открыть...",		9,"Ctrl+O"
RMS_SAVE		equ "&Сохранить...",		9,"Ctrl+S"
RMS_SAVEAS		equ "Сохранить &как...",	9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "Сохранить со с&жатием..."
RMS_IMPORT		equ "&Импорт...",		9,"Ctrl+I"
RMS_EXPORT		equ "&Экспорт...",		9,"Ctrl+P"
RMS__MRU		equ "Недавние файлы"
RMS_EXIT		equ "В&ыход",			9,"Alt+F4"

RMS__EDIT		equ "&Правка"
RMS_TEST		equ "Про&тестировать"
RMS_DELETE		equ "&Удалить",			9,"Del"
RMS_FONTS		equ "Настройки &шрифта..."
RMS_SETPATHS		equ "Задать п&ути..."
RMS_CONFIG		equ "&Конфигурация..."

RMS__SEARCH		equ "&Поиск"
RMS_FIND		equ "&Найти...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "Найти &предыдущее",	9,"Shift+F3"
RMS_FINDDOWNWARD	equ "Найти &следующее",		9,"F3"
RMS_QUERYCONSTANT	equ "&Константа запроса..."

RMS__VIEW		equ "&Вид"
RMS_STATUSBAR		equ "&Строка состояния"
RMS_SHOWHIDETOOLBAR	equ "&Панель инструментов"
RMS_BINARYPANE		equ "&Двоичный"
RMS_EXPAND_ALL		equ "&Распахнуть все",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "С&вернуть все",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "&Заворачивать строки"
RMS_REFRESH		equ "О&бновить"

RMS__HELP		equ "&Справка"
RMS_ABOUT		equ "&О программе..."
