LANGUAGE LANG_CHINESE, SUBLANG_SYS_DEFAULT

; IDR_MAINMENU
RMS__FILE		equ "文件(&F)"
RMS_NEW			equ "新建(&N)",			9,"Ctrl+N"
RMS_OPEN		equ "打开(&O)...",		9,"Ctrl+O"
RMS_SAVE		equ "覆写(&S)...",		9,"Ctrl+S"
RMS_SAVEAS		equ "另存为(&A)...",		9,"Shift+Ctrl+S"
RMS_SAVEASCOMP		equ "另存压缩(&M)..."
RMS_IMPORT		equ "导入(&I)...",		9,"Ctrl+I"
RMS_EXPORT		equ "导出(&E)...",		9,"Ctrl+P"
RMS__MRU		equ "最近使用的文件夹"
RMS_EXIT		equ "退出(&X)",			9,"Alt+F4"

RMS__EDIT		equ "编辑(&E)"
RMS_TEST		equ "效果测试(&T)"
RMS_DELETE		equ "删除(&D)",			9,"Del"
RMS_FONTS		equ "字体设置(&F)..."
RMS_SETPATHS		equ "设置PATH(&P)..."
RMS_CONFIG		equ "设置(&C)..."

RMS__SEARCH		equ "搜索(&S)"
RMS_FIND		equ "查询(&F)...",		9,"Ctrl+F"
RMS_FINDUPWARD		equ "向上搜索(&U)",		9,"Shift+F3"
RMS_FINDDOWNWARD	equ "向下搜索(&D)",		9,"F3"
RMS_QUERYCONSTANT	equ "查询常量(&Q)..."

RMS__VIEW		equ "界面显示(&V)"
RMS_STATUSBAR		equ "状态栏(&S)"
RMS_SHOWHIDETOOLBAR	equ "工具栏(&T)"
RMS_BINARYPANE		equ "二进制模式(&B)"
RMS_EXPAND_ALL		equ "全部展开(&X)",		9,"Ctrl+K"
RMS_COLLAPSE_ALL	equ "全部折叠(&O)",		9,"Ctrl+L"
RMS_WORD_WRAP		equ "自动换行(&W)"
RMS_REFRESH		equ "更新到最新信息(&F)"

RMS__HELP		equ "帮助(&H)"
RMS_ABOUT		equ "关于(&A)..."
