; line for directory:
;		RT_VERSION,versions,\
;
; lines for folder:
;	resource versions,\
;		1,LANG_NEUTRAL,version

versioninfo version,VOS__WINDOWS32,VFT_APP,VFT2_UNKNOWN,LANG_ENGLISH+SUBLANG_DEFAULT,0,\
\; these three/two are displayed in explorer tooltip/tile:
	'FileDescription',	'This program does nothing.',\
	'CompanyName',		'Dank-Orb™',\
	'FileVersion',		'0.0.0.0',\
\; these are visible in file properties, Details tab:
	'LegalCopyright',	'© All rights reserved.',\
	'LegalTrademarks',	'bitRAKE™',\
	'OriginalFilename',	'filename.exe',\
	'ProductName',		'Parenthetical',\
	'ProductVersion',	'0.0.0.0',\
\; custom fields, last displayed in WinXP:
	'Comments',		"Don't believe everything you read.",\
	'PrivateBuild',		'0.0.0.1',\
	'SpecialBuild',		'true',\
	'InternalName',		'bug_quarry'
